# Die Ziele der Gemeinde  {#die-ziele-der-gemeinde}

**Zusammenfassung:** Man kann aus der Bibel folgende Ziele der Gemeinde ableiten, wobei das erste Ziel die zwei letzten beinhaltet:

- *Gott verherrlichen*: nicht nur während dem Gottesdienst sonder durch unseren ganzen Wesen (Gedanken, Handeln, etc.)
- *sich als Mitchristen gegenseitig erbauen und ausrüsten*: damit wir eins sein können, wie der Sohn und der Vater eins sind, damit wir Gott/Jesus ähnlicher werden, damit letztlich  Gott dadurch verherrlicht wird.
- *das Evangelium verkündigen*: damit andere Menschen von dem ewigen Tod gerettet werden können, damit wir die Grösse Gottes verkündigen, damit letztlich  Gott dadurch verherrlicht wird.

Jede Gemeindeaktivität sollte in Hinblick auf das erste Ziel (Gott verherrlichen) sowie auf das zweite oder dritte Ziel geprüft werden. 

Gutes "Gemeindeprogramm":

```{block, type='rmdquote'}
«Und sie blieben beständig in der Lehre der Apostel und in der Gemeinschaft und im Brotbrechen und in den Gebeten.» 

-- Apostelgeschichte 2.42
```

***

*Übersetzung aus einem Auszug aus «Théologie systématique» (englisch «Systematic Theology») von Wayne Grudem, 2012, ISBN  9782755001051*

Wir können denken, dass die Gemeinde aus drei Gründen existiert: um Gott zu dienen, um den Gläubigen zu dienen und um der Welt zu dienen.

## 1. Gott dienen: Anbetung

In Bezug auf Gott besteht der Zweck der Gemeinde darin, ihn anzubeten. Paulus lädt die Gemeinde in Kolossä ein, "Psalmen, Hymnen und Lieder von ganzem Herzen, vom Geist inspiriert, Gott zu singen, um eure Dankbarkeit Gott gegenüber auszudrücken" (Kol 3,16). Gott hat uns auserwählt und vorher in Christus dazu bestimmt, "seine Herrlichkeit zu feiern" (Eph 1,12). Die Anbetung in der Gemeinde bereitet uns nicht einfach auf etwas anderes vor: Sie ist die Erfüllung des Zwecks der Gemeinde in Bezug auf ihren Herrn. Deshalb fordert Paulus, nachdem er die Epheser ermahnt hat, die Zeit einzulösen, sie auf, sich ständig vom Geist erfüllen zu lassen und "den Herrn von ganzem Herzen mit euren Liedern und Psalmen zu preisen" (Eph 5,16-19).

## 2. Den Gläubigen dienen: Ausbildung

Nach der Heiligen Schrift hat die Gemeinde die Pflicht, diejenigen zu nähren, die bereits gläubig sind, und sie zur Glaubensreife zu führen. Paulus erklärt, dass sein Ziel nicht einfach darin besteht, die Menschen zum rettenden Glauben zu führen, sondern "jeden Menschen vollkommen in Christus Jesus darzustellen." (Kol 1,28). Und er sagt der Gemeinde von Ephesus, dass Gott der Gemeinde Menschen mit verschiedenen Gaben gegeben hat, "zur Zurüstung der Heiligen, für das Werk des Dienstes, für die Erbauung des Leibes des Christus, bis wir alle zur Einheit des Glaubens und der Erkenntnis des Sohnes Gottes gelangen, zur vollkommenen Mannesreife, zum Mass der vollen Grösse des Christus" (Eph 4,12-13). Es widerspricht eindeutig dem neutestamentlichen Modell, zu glauben, dass unser einziger Zweck darin besteht, Menschen zum rettenden Glauben zu führen. Unser Ziel als Gemeinde muss es sein, jeden Christen vor Gott erscheinen zu lassen, "vollkommen in Christus Jesus" (Kol 1,28).

## 3. Der Welt dienen: Evangelisation und Barmherzigkeit

Jesus wies seine Jünger an, "alle Völker zu Jüngern zu machen" (Mt 28,19). Dieses Werk der Evangelisation, der Verkündigung des Evangeliums, ist die vorrangige Verantwortung der Gemeinde gegenüber der Welt1. Aber das Werk der Evangelisation muss von Werken der Barmherzigkeit, der Sorge um die Armen und Bedürftigen im Namen des Herrn begleitet sein. Obwohl die Betonung im Neuen Testament auf der materiellen Hilfe für diejenigen liegt, die Teil der Gemeinde sind (Apg 11,29; 2 Kor 8,4; 1 Joh 3,17), bekräftigt das Neue Testament, dass den Ungläubigen geholfen werden muss, auch wenn sie nicht dankbar sind oder die Botschaft des Evangeliums nicht annehmen. Jesus sagt es uns:
Vielmehr liebt eure Feinde und tut Gutes und leiht, ohne etwas dafür zu erhoffen; so wird euer Lohn groß sein, und ihr werdet Söhne des Höchsten sein, denn er ist gütig gegen die Undankbaren und Bösen. Darum seid barmherzig, wie auch euer Vater barmherzig ist. (Lk 6:35-36)

Was Jesus meint, ist, dass wir Gott nachahmen müssen, indem wir gut zu den Undankbaren und Bösen sind. Ausserdem haben wir das Beispiel Jesu, der nicht versuchte, nur diejenigen zu heilen, die ihn als Messias akzeptierten. Als grosse Menschenmengen zu ihm kamen, "er legte einem jeden von ihnen die Hände auf und heilte sie" (Lk 4,40). Dies sollte uns ermutigen, Werke der Barmherzigkeit zu tun und für Heilung und andere Nöte im Leben von Gläubigen und Ungläubigen gleichermassen zu beten. Werke der Barmherzigkeit für die Welt können auch die Teilnahme an staatsbürgerlichen Aktivitäten oder Bemühungen zur Einflussnahme auf die Regierungspolitik umfassen, damit diese besser mit den biblischen Prinzipien der Moral übereinstimmt. In Gebieten, in denen es systematische Ungerechtigkeit in der Behandlung der Armen und/oder ethnischer oder religiöser Minderheiten gibt, sollte die Gemeinde auch beten und, wenn sie die Gelegenheit dazu hat, sich gegen diese Ungerechtigkeit aussprechen. Dies sind verschiedene Wege für die Gemeinde, ihr Werk der Evangelisation in der Welt zu vollenden und dem Evangelium, zu dem sie sich bekennt, Glaubwürdigkeit zu verleihen. Aber diese Werke der Barmherzigkeit für die Welt sollten niemals eine echte Evangelisation oder die anderen oben erwähnten Pflichten der Gemeinde gegenüber Gott und den Gläubigen ersetzen.

## 4. Die Aufrechterhaltung eines Gleichgewichts zwischen diesen Zielen

Nachdem diese drei Ziele für die Gemeinde vorgestellt worden sind, werden Sie sich vielleicht fragen, welches das wichtigste ist oder ob es möglich ist, eines der drei Ziele, das als weniger wichtig als die anderen angesehen wird, zu vernachlässigen.

Wir müssen antworten, dass diese drei Ziele der Gemeinde Gebote des Herrn in der Heiligen Schrift sind. Daher sind alle drei wichtig und keiner kann vernachlässigt werden. Tatsächlich wird eine starke Gemeinde in allen drei Bereichen effektiv arbeiten. Wir sollten uns vor jedem Versuch hüten, den Zweck der Gemeinde auf nur einen der drei zu reduzieren und ihn zur Priorität zu machen. Der Versuch, einem dieser Ziele Vorrang einzuräumen, wird in der Tat immer dazu führen, dass wir die beiden anderen vernachlässigen. Eine Gemeinde, die sich nur um den Gottesdienst bemüht, wird am Ende den Gläubigen eine geringere Qualität der Lehre bieten, und ihre Mitglieder werden ein oberflächliches Verständnis der Heiligen Schrift haben und es wird ihnen an Reife in ihrem christlichen Leben fehlen. Wenn sie beginnt, auch die Evangelisation zu vernachlässigen, wird die Gemeinde aufhören, zu wachsen und andere zu beeinflussen; sie wird sich nur schwer entwickeln können und schliesslich verkümmern.

Eine Gemeinde, die die Erbauung der Gläubigen zu einem vorrangigen Ziel vor den beiden anderen macht, wird dazu neigen, Christen hervorzubringen, die die biblische Lehre sehr gut kennen, aber in ihrem christlichen Leben geistliche Trockenheit zeigen, weil sie sehr wenig von der Freude wissen, Gott anzubeten oder mit anderen über Christus zu sprechen.
Aber eine Gemeinde, die die Evangelisation zu einer solchen Priorität macht und die anderen beiden Ziele vernachlässigt, wird am Ende auch unreife Christen hervorbringen, die auf zahlenmässigem Wachstum bestehen, aber Gott ohne aufrichtige Liebe anbeten und denen es in ihrem Leben an lehrmässiger Reife und persönlicher Heiligkeit mangelt. Eine gesunde Gemeinde wird immer wieder gleichzeitig auf allen drei dieser Ziele bestehen.

Es ist jedoch normal, dass Einzelpersonen, anders als Gemeinden, dem einen oder anderen dieser Ziele der Gemeinde relative Priorität einräumen. Da wir wie ein Leib mit vielfältigen geistlichen Gaben und Fähigkeiten sind, ist es normal, dass wir den grössten Teil unserer Bemühungen der Erfüllung des Zwecks der Gemeinde widmen, der am besten den Gaben und Interessen entspricht, die Gott uns gegeben hat. Offensichtlich ist kein Gläubiger verpflichtet, zu versuchen, genau ein Drittel seiner Zeit in der Gemeinde für den Gottesdienst, ein Drittel für die Lehre anderer Gläubiger und ein Drittel für Evangelisation oder Werke der Barmherzigkeit aufzuwenden. Wer die Gabe der Evangelisation hat, sollte natürlich Zeit für den Gottesdienst und die Fürsorge für andere Gläubige aufwenden, aber es ist normal, dass er den grössten Teil seiner Zeit der evangelistischen Arbeit widmen sollte.

Ebenso ist es nicht ungewöhnlich, dass derjenige, der die Gabe hat, die Momente des Gottesdienstes zu leiten, am Ende einen grossen Teil seiner Zeit in der Gemeinde damit verbringt, sie vorzubereiten und zu leiten. Dies ist nur ein Spiegelbild der Vielfalt der Gaben, die Gott seiner Gemeinde zur Verfügung gestellt hat.

*Übersetzung aus einem Auszug aus «Théologie systématique» (englisch «Systematic Theology») von Wayne Grudem, 2012, ISBN  9782755001051*
