# Siehst du das Lamm {#siehst-du-das-lamm}

«Siehst du das Lamm» ist ein Lied von Albert Frey geschrieben. Wir gehen durch jede Strophe und versuchen die Hintergründe zu erklären.


## Siehst du das Lamm, in jener Nacht? (Strophe 1)

```{block, type='rmdquote'}
Siehst du das Lamm, in jener Nacht?
Sein Blut an Türen angebracht.
Es rettet vor der des Todes Hand.
Das Volk kann ziehn in neues Land.
```

Das Volk Israel war Sklave in Ägypten und der Pharao wollte das Volk Israel nicht wegziehen lassen. Gott bestrafte Ägypten mit zehn Plagen. Die zehnte Plage war das Sterben von allen Erstgeborenen. Die Israeliten wurden aber aufgefordert, ein Lamm zum essen zu schlachten und sein Blut an den Türpfosten zu streichen, als Schutzzeichen vor der Zehnten Plage (2. Mose 12).

Gott rettete sein Volk durch sein Gericht über Ägypten. Ein Glaubensschritt war dafür nötig. Der Passah-Lamm müsste stellvertretend für den Erstgeborenen sterben. Von nun an gehörten die Erstgeborenen Gott. 

## Siehst du das Lamm, dort am Altar? (Strophe 2)

```{block, type='rmdquote'}
Siehst du das Lamm, dort am Altar?
Des Volkes Schuld von einem Jahr
Liegt nun auf ihm, es kauft sie los,
Das Opferlamm, so makellos.
```

Im dritten Buch Mose, Kapitel 16, lesen wir, dass es sich eigentlich um zwei Ziegenböcke und nicht um ein Lamm handelt. Einmal pro Jahr wurde für das Volk Israel Sühnung erwirkt, um das Volk von all seinen Sünden vor dem Herrn zu reinigen.

Zwei makellose Ziegenböcke wurden ausgewählt. Eine der Ziegen wurde symbolisch mit der Schuld des Volkes beladen und in die Wüste gejagt, um dort zu sterben. Die Sünde wurde also weggenommen, entfernt. Die andere Ziege wurde geschlachtet. Ihr Blut wurde direkt zu Gott ins Innerste des Heiligtums gebracht. Das Blut war ein Symbol für das Leben und das Leben gehört Gott. Da die Folge der Sünde der Tod ist, wurde Blut, d.h. Leben, stellvertretend vergossen.

Das levitische System funktioniert nur, wenn der Anbeter glaubt, dass Gott in der Mitte des Volkes ist, dass Gott heilig ist, dass Opfer zur Reinigung dargebracht werden müssen, und wenn er so lebt, dass es diesen Überzeugungen entspricht (z.B. 3. Mose 15.31; 22.9). 

## Siehst du das Lamm dort an dem Kreuz? (Strophe 3)

```{block, type='rmdquote'}
Siehst du das Lamm dort an dem Kreuz?
Bezahlt den höchsten Liebespreis.
Es trägt die Last der ganzen Welt,
Von Leid und Schmerzen ganz entstellt.
```

So wie Israel aus der Sklaverei in Ägypten erlöst wurde, sind die, die an Christus glauben, von der Sklaverei der Sünde erlöst, mit einem Preis erkauft (z.B. 1. Korinther 6.20). Wie Israel am Passahfest erlöst wurde, so ist Christus, das Passahlamm, geschlachtet worden (Johannes 1.26-36; 1. Korinther 5.7). 

So wie ein Ziegenbock mit der Schuld des Volkes beladen wurde und in die Wüste gejagt wurde, so wurde Jesus mit der Sünde der Welt beladen und ausserhalb von Jerusalem weggebracht. Sowie der andere Ziegenbock geschlachtet wurde, wurde Jesus am Kreuz getötet und er liess sein Blut stellvertretend für uns giessen (1 Petrus 2:24, Kolosser 2.13-15) .

Jesus zeigte die Liebe Gottes, indem er wie ein Lamm starb. Er trug das Gericht Gottes an unsere Stelle, damit die, die an ihn glauben, gerettet werden.

## Siehst du das Lamm dort auf dem Thron? (Strophe 4)

```{block, type='rmdquote'}
Siehst du das Lamm dort auf dem Thron?
Der Vater gibt die Macht dem Sohn,
Denn würdig ist allein nur er.
Die Völker singen: Heilig, Herr.
```

In Offenbarung 5 sieht Johannes ein Buch mit sieben Siegeln versiegelt. Johannes weint, weil niemand würdig ist, das Buch zu öffnen. «Und einer von den Ältesten spricht zu mir: Weine nicht! Siehe, es hat überwunden der Löwe, der aus dem Stamm Juda ist, die Wurzel Davids, um das Buch zu öffnen und seine sieben Siegel zu brechen!»

Da schaut Johannes und was sieht er? Nicht einen Löwen aber ein Lamm, das auf dem Thron sitzt. Dann wird ein neues Lied gesungen:

«Würdig bist du, das Buch zu empfangen und seine Siegel zu öffnen, denn du bist geschlachtet worden und hast erkauft mit deinem Blut für Gott Menschen aus jedem Stamm und jeder Sprache, aus jedem Volk und jeder Nation. 10 Und du hast sie für unseren Gott zu einem Königreich und zu einer Priesterschaft gemacht, und sie werden herrschen auf Erden.»

Dann hört er die Engel sagen:

«Würdig ist das Lamm, das geschlachtet worden ist, zu empfangen Kraft und Reichtum und Weisheit und Stärke und Ehre und Ruhm und Lob!»

Es ist vermutlich der Grund, weshalb der Refrain dieser Stelle im Lied von Albert Frey kommt:

```{block, type='rmdquote'}
Wir beten an
Wir beten an
Wir beten an, das Gottes Lamm
```

## Siehst du das Lamm auf seinem Arm? (Strophe 5)

```{block, type='rmdquote'}
Siehst du das Lamm auf seinem Arm?
Der gute Hirte hält es warm.
Er ließ die Neunundneunzig stehn.
Es soll ihm keins verloren gehen.
Es soll ihm keins verloren gehen.
```

Die letzte Strophe ist das Gleichnis vom verlorenen Schaf (Lukas 15.1-7). Der gute Hirte verlässt seine 99 Schafe, um sein verlorenes Schaf zu suchen und zu finden. Die Schlussfolgerung des Gleichnisses: Es wird mehr Freude im Himmel für einen Sünder geben, der Busse tut, als für 99 Gerechte, die keine Busse brauchen (Lukas 15.7). 

Dieses Gleichnis ist von zwei weiteren ähnlichen Gleichnissen gefolgt: das Gleichnis von der verlorenen Drachme (Lukas 15.8-10) und das Gleichnis vom verlorenen Sohn (Lukas 15.11-32). Der Kontext für diese 3 Gleichnisse ist im ersten Vers vom Kapitel 15 gegeben: «die Pharisäer und die Schriftgelehrten murrten und sprachen: [Jesus] nimmt Sünder an und isst mit ihnen!». Mit den drei Gleichnisse zeigt Jesus den Pharisäer und Schriftgelehrten, dass er nicht gekommen ist, Gerechte zu berufen, sondern Sünder zur Busse (Lukas 5.31-32). Alle zum Fest eingeladen sind aber nicht alle wollen diese Einladung annehmen, wie z.B. der Bruder vom verlorenen Sohn. Letzterer könnte ein Bild für die «gerechten» Pharisäer und Schriftgelehrten sein: die merken nicht einmal, dass sie verloren sind.

Der letzte Satz von der Strophe 5 kann als eine Anspielung an Johannes 10.27-29 wahrgenommen. Jesus sagte: «Meine Schafe hören meine Stimme, und ich kenne sie, und sie folgen mir nach; und ich gebe ihnen ewiges Leben, und sie werden in Ewigkeit nicht verlorengehen, und niemand wird sie aus meiner Hand reissen. Mein Vater, der sie mir gegeben hat, ist grösser als alle, und niemand kann sie aus der Hand meines Vaters reissen.» (Johannes 10.27-29). Was für eine Zusage! Wenn du Jesus gehörst, gehörst du ihm für immer.

---

```{block, type='rmdquote'}
Denn ihr wisst ja, dass ihr nicht mit vergänglichen Dingen, mit Silber oder Gold, losgekauft worden seid aus eurem nichtigen, von den Vätern überlieferten Wandel, sondern mit dem kostbaren Blut des Christus als eines makellosen und unbefleckten Lammes.»  1. Petrus 1.18-19
```
