# Schon und noch nicht  {#schon-und-noch-nicht}


```{block, type='rmdquote'}
«Indem er ihm aber alles unterworfen hat, hat er nichts übriggelassen, das ihm nicht unterworfen wäre. Jetzt aber sehen wir noch nicht, daß ihm alles unterworfen ist;»

-- Hebräer 2.8
```



Wir leben aber noch in einer Spannung: wir sind...

- schon in Christus adoptiert (Römer 8,15), aber noch nicht adoptiert (Römer 8,23);
- schon in Christus erlöst (Epheser 1:7), aber noch nicht erlöst (Epheser 4:30);
- schon geheiligt in Christus (1. Korinther 1:2), aber noch nicht geheiligt (1. Thessalonicher 5:23-24);
- schon in Christus gerettet (Epheser 2:8), aber noch nicht gerettet (Römer 5:9);
- schon in Christus auferweckt (Epheser 2,6), aber noch nicht auferweckt (1. Korinther 15,52).

Wir leben in einer theologischen Spannung. Durch den Glauben an Christus gehören all diese geistlichen Segnungen bereits uns, aber der volle Genuss dieser Segnungen gehört uns noch nicht. Dies ist das Leben des Glaubens: "die Gewissheit der Dinge, die in der Zukunft erhofft werden", und "die Überzeugung von Dingen, die in der Gegenwart nicht gesehen werden" (Hebräer 11,1). Dies ist das Leben zwischen den Zeiten.

Wenn wir diese Denkweise nicht verstehen, wird die theologische Spannung, in der wir leben, zu einer theologischen Katastrophe. Wir werden die Heilige Schrift unweigerlich falsch lesen. Und wenn wir die Heilige Schrift falsch lesen, werden wir irregeführte Leben führen. Um ein Beispiel zu nennen: Das Nichtverstehen des «schon und noch nicht» Rahmens könnte dazu führen, dass eine Person glaubt, es gäbe zwei Wege zur Rettung. Die anfängliche Errettung hängt ganz von Gott ab (Epheser 2,8), aber die endgültige Errettung hängt ganz von uns ab (Römer 5,9), wobei der praktische Schaden eine legalistische Denkweise ohne das Evangelium ist.

Zum vertiefen (Artikel auf English):
https://www.desiringgod.org/articles/already-not-yet
