# Gottes Souveränität und menschliche Verantwortung  {#gottes-souveraenitaet-und-menschliche-verantwortung}

*Auszug aus dem Buch "Praying with Paul" von D. A. Carson, Übersetzung aus dem Englischen.*

    
Ich möchte damit beginnen, zwei Wahrheiten zu formulieren, die beide nachweislich immer wieder in der Bibel gelehrt oder veranschaulicht werden:

1. Gott ist absolut souverän, aber seine Souveränität wirkt nie so, dass die Verantwortung des Menschen verringert wird.
2. Menschen sind verantwortliche Geschöpfe - das heisst, sie wählen, sie glauben, sie gehorchen nicht, sie reagieren, und ihre Entscheidungen haben eine moralische Bedeutung; aber die menschliche Verantwortung hat in der Schrift niemals die Funktion, Gottes Souveränität zu schmälern oder Gott absolut kontingent zu machen.

Mein Argument ist, dass beide Thesen in der Bibel gelehrt und veranschaulicht werden. Ein Teil unseres Problems ist der Glaube, dass beide wahr sind. Wir neigen dazu, das eine zu benutzen, um das andere zu schmälern; wir neigen dazu, das eine auf Kosten des anderen zu betonen. Aber eine verantwortungsvolle Lektüre der Schrift verbietet einen solchen Reduktionismus. Wir könnten damit beginnen, einen Blick auf das große Bild zu werfen. Sprüche 16 stellt Gott als so absolut souverän dar, dass, wenn Sie oder ich einen Würfel werfen, Gott bestimmt, welche Seite herauskommt (16,33). "Der HERR arbeitet alles zu seinem rechten Ende aus - auch die Bösen für den Tag des Unheils" (16,4). "In ihren Herzen planen die Menschen ihren Weg, aber der HERR bestimmt ihre Schritte" (16,9). "Warum sagen die Völker: 'Wo ist ihr Gott?' Unser Gott ist im Himmel; er tut, was ihm gefällt" (Ps. 115,2-3).

Wenn die Vögel satt werden, so Jesus, dann deshalb, weil der Vater sie füttert (Mt 6,26); wenn Wildblumen wachsen, dann deshalb, weil Gott das Gras bekleidet (6,30). Gott steht also hinter den sogenannten natürlichen Prozessen. Deshalb sprechen die biblischen Schreiber lieber davon, dass der Herr den Regen schickt, als einfach zu sagen: "Es regnet" - und das, obwohl sie den Wasserkreislauf genau kannten. Die Propheten verstanden die Tragweite von Gottes Herrschaft: 
"Der Herr weiß, dass das Leben der Menschen nicht ihr eigenes ist; es steht ihnen nicht zu, ihre Schritte zu lenken" (Jer. 10,23). "Der HERR tut, was ihm gefällt, in den Himmeln und auf der Erde, in den Meeren und in allen ihren Tiefen" (Ps 135,6). Die Stelle in Epheser 1,3-14 ist so stark wie jede andere: Gott "wirkt alles nach dem Vorsatz seines Willens" (Eph. 1,11). Auf geheimnisvolle Weise und ohne selbst mit dem Bösen befleckt zu sein, steht Gott hinter unbeabsichtigtem Totschlag (2. Mose 21,13), familiärem Unglück (Rut 1,13), nationalem Unheil (Jes. 45,6-7), persönlichem Kummer (Läm. 3,32-33.37-38) und sogar Sünde (2. Sam. 24,1; 1. Kön. 22,21ff.). In keinem dieser Fälle wird jedoch jemals die menschliche Verantwortung gemindert. Obwohl es also Gott in seinem Zorn ist, der David zu der verbotenen Volkszählung anstiftet (2. Sam. 24,1), wird David dennoch für sein Handeln zur Rechenschaft gezogen.

Die zweite meiner beiden Aussagen wird von der Schrift nicht weniger stark unterstützt. Es gibt zahllose Stellen, an denen Menschen befohlen wird, zu gehorchen, zu wählen, zu glauben, und sie zur Rechenschaft gezogen werden, wenn sie das nicht tun. Gott selbst hält bewegende Appelle bereit, um uns zur Umkehr zu bewegen, weil er am Tod der Gottlosen kein Gefallen findet (Jes. 30:18; 65:2; Lam. 3:31-36; Hes. 18:30-32; 33:11). Zu seiner Zeit kann Josua Israel mit diesen Worten herausfordern: "Fürchte nun den HERRN und diene ihm mit aller Treue. . . . Wenn es euch aber nicht gefällt, dem HERRN zu dienen, dann wählt euch heute selbst, wem ihr dienen wollt. . . . Was aber mich und mein Haus betrifft, so wollen wir dem Herrn dienen" (Jos 24,14-15). Die befehlende Aufforderung des Evangeliums selbst übernimmt eine tiefe Verantwortung: "Wenn du mit deinem Mund bekennst: 'Jesus ist der Herr', und in deinem Herzen glaubst, dass Gott ihn von den Toten auferweckt hat, wirst du gerettet werden. . . . Wie die Schrift sagt: 'Jeder, der an ihn glaubt, wird niemals zuschanden werden'" (Röm. 10:9, 11). Natürlich stellt nichts davon Gottes Souveränität in Frage: Nur wenige Verse vorher finden wir den Apostel, der die Schrift (2. Mose 33,19) zitiert, um zu beweisen, dass "Gott sich erbarmt, über wen er sich erbarmen will, und er verhärtet, wen er verhärten will"
(Röm. 9:18).

Hunderte von Stellen könnten untersucht werden, um zu zeigen, dass die Bibel sowohl davon ausgeht, dass Gott souverän ist als auch, dass die Menschen für ihr Handeln verantwortlich sind. So schwer es für viele Menschen in der westlichen Welt auch ist, mit beiden Wahrheiten gleichzeitig klarzukommen, so viel interpretatorischen Einfallsreichtum braucht es, um zu argumentieren, dass die Bibel beides nicht unterstützt. In der Tat unterstützt die Bibel nicht nur beide Wahrheiten in einer großen Anzahl von ungleichen Passagen, sondern beide Wahrheiten kommen auch in vielen Passagen zusammen. 



```{block, type='rmdyou'}
Lese die folgenden Stellen in der Bible und versuche für jede Stelle herauszufinden, wie sich die Souveränität Gottes und die menschliche Verantwortung sich ausdrücken.

- 1. Mose 50,19–20 (Josef)
- 2. Samuel 24
- Jesaja 10,5–19
- Johannes 6,37–40
- Philipperbrief 2,12–13
- Apostelgeschichte 18,9–10
- Apostelgeschichte 4,23–30
```

## Schlussfolgerung

Est es wichtig, eine entscheidende Lektion aus der vorherigen Diskussion zu ziehen. Geben wir zu, dass die Bibel darauf besteht, dass Gott absolut souverän ist und die Menschen moralisch verantwortliche Geschöpfe sind; geben wir zu, dass Gott selbst sowohl transzendent als auch persönlich ist. 

Geben wir freimütig zu, dass dies ein erhebliches Maß an Geheimnis beinhaltet. Die Fragen, die wir uns dann stellen müssen, sind diese: Wie können wir sicherstellen, dass diese komplementären Paare von Wahrheiten in unserem Leben in der richtigen Weise wirken? Wenn sie so geheimnisvoll sind, laufen wir dann nicht immer Gefahr, diese Wahrheiten in einer Weise zu gebrauchen, die das Geheimnis leugnet oder im Widerspruch zu etwas anderem steht, das wir wissen sollten?

Die Antwort ist einfach, hat aber tiefgreifende Auswirkungen. Wir müssen unser Bestes tun, um sicherzustellen, dass diese komplementären Wahrheiten in unserem Leben auf dieselbe Weise funktionieren, wie sie im Leben der Gläubigen funktionieren, die in der Heiligen Schrift beschrieben werden. Wie funktioniert zum Beispiel die Erwählung in der Schrift? Wie sollte die Erwählung in unserem Leben funktionieren? Sie funktioniert in der Schrift nie, um Fatalismus zu fördern; sie funktioniert nie, um den evangelistischen Eifer zu dämpfen. Sie dient immer wieder dazu, das Wunder der Gnade zu betonen (Johannes 6,68-70; Röm. 9). Sie hat unter anderem auch die Funktion, die Gewissheit geistlicher Fruchtbarkeit unter Gottes Volk zu gewährleisten (Johannes 15,16) und die Ausdauer in der Evangelisation zu fördern (Apostelgeschichte 18,9-10).Wie funktionieren die ständigen Ermahnungen zum Glauben und Gehorsam in der Schrift? Sie haben nie die Funktion, Gott als grundsätzlich am Ende seiner eigenen Ressourcen und völlig abhängig von uns darzustellen; sie reduzieren Gott nie auf das absolut Kontingente. Sie reduzieren Gott nie auf das absolut Zufällige. Vielmehr dienen sie dazu, unsere Verantwortung zu erhöhen, die Dringlichkeit der Schritte zu betonen, die wir unternehmen müssen, und uns zu zeigen, was die einzig richtige Antwort auf diese Art von Gott ist.

Wie funktioniert die wiederholte Wahrheit von Gottes souveräner Vorsehung in der Heiligen Schrift? Sie dient niemals dazu, gleichgültigen Fatalismus zu autorisieren; sie erlaubt mir niemals, moralisch gleichgültig zu sein mit der Begründung, dass ich sowieso nichts dafür kann. Vielmehr funktioniert die biblische Betonung der Souveränität Gottes auf ganz andere Weise. Zum Beispiel gibt sie mir Gründe für den Glauben, dass alles unter Gottes gnädiger Kontrolle steht, so dass sich alles zum Guten wenden wird im Leben der
im Leben des Volkes Gottes zum Guten wenden wird (Röm. 8,28).


