# Die Hochzeit des Lammes  {#die-hochzeit-des-lammes}


> Und ich, [Johannes] hörte etwas wie die Stimme einer grossen Volksmenge und wie das Rauschen vieler Wasser und wie der Schall starker Donner, die sprachen: Hallelujah! Denn der Herr, Gott, der Allmächtige, hat die Königsherrschaft angetreten! 7 Laßt uns fröhlich sein und jubeln und ihm die Ehre geben! Denn die Hochzeit des Lammes ist gekommen, und seine Frau hat sich bereit gemacht. 8 Und es wurde ihr gegeben, sich in feine Leinwand zu kleiden, rein und glänzend; denn die feine Leinwand ist die Gerechtigkeit der Heiligen.
9 Und [der Angel] sprach zu mir: Schreibe: Glückselig sind die, welche zum Hochzeitsmahl des Lammes berufen sind! Und er sprach zu mir: Dies sind die wahrhaftigen Worte Gottes! -- Johannes 19:6-9


Die Bibel erzählt eine Liebesgeschichte. Eine echte Liebesgeschichte mit echter und treuer Liebe. Im Alten Testament vergleicht Gott seine Liebe zu Israel mit der Liebe zu einer Braut. Im Neuen Testament ist die Braut die Gemeinde, die von dem Bräutigam Jesus geliebt ist.

Ist die Gemeinde bereits mit Jesus verheiratet? Oder ist sie nur mit Jesus verlobt? Wie heiratete man zur Zeit Jesu?

Zur Zeit Jesus bestand die jüdische Hochzeit aus drei Phasen:

**Phase 1**: Der Bräutigam verlässt das Haus seines Vaters und reist zum Haus der Braut, um sie für einen bestimmten Preis zu "kaufen". Dann wird der Ehevertrag abgeschlossen, und von diesem Moment an ist die Braut ausschliesslich für ihren Bräutigam bestimmt. Es ist üblich, dass der Bräutigam und die Braut aus einem Becher Wein trinken, über den ein Verlobungssegen gesprochen wurde.

**Phase 2**: Der Bräutigam kehrt in das Haus Haus seines Vaters zurück, um eine Wohnung einzurichten, in dem er und seine zukünftige Braut wohnen werden.

**Phase 3**: Wenn die Zeit gekommen ist, geht der Bräutigam begleitet von Freunde zu seiner Braut zurück.  Der genaue Zeitpunkt seiner Ankunft war normalerweise nicht im Voraus bekannt. Die Ankunft des Bräutigams wurde mit einem Rufen angekündigt. Der Bräutigam nimmt die Braut zu sich und dann folgt ein 7-tägiges fröhliches Hochzeitsfest!

Wenn man das Neue Testament im Licht dieser jüdischen Tradition liest, werden einige Worte und Gleichnisse Jesu in vielerlei Hinsicht verständlicher! Im Folgenden wird gezeigt, dass der jüdische Hochzeitsprozess ein Schatten von Gottes Rettungsplan durch Christus ist. In diesem Sinn schreibt Paulus, dass die Ehe ein grosses Geheimnis ist, *das auf Christus und auf die Gemeinde deutet* (Epheser 5:32). Mit Geheimnis meint er etwas, «das von ewigen Zeiten her verschwiegen war, das jetzt aber offenbar gemacht worden ist» (Römer 16:25-26, siehe auch Galater 4:4; Epheser 1:10, Kolosser 1:25-26).


**Phase 1**: Jesus hat das Haus seines Vaters (den Himmel) verlassen und ist in das Haus seiner zukünftigen Braut (die Erde) gereist, um sie für einen Preis, nämlich sein eigenes Blut, zu kaufen (1. Korinther 7:23). Der Abendmahlswein ist ein Symbol für den Bund zwischen Christus und seine Braut (Lukas 22:20).

**Phase 2**: Jesus geht dann in das Haus seines Vaters, um dort eine Wohnung zu errichten (die himmlische Jerusalem, Offenbarung 21:1-22:5). Deshalb sagte er zu seinen Jüngern: "Das Haus meines Vaters hat viele Zimmer; wenn es nicht so wäre, hätte ich euch dann gesagt, dass ich dorthin gehe, um euch eine Wohnung zu bereiten? Und wenn ich hingehe und euch eine Stätte bereite, will ich wiederkommen und euch zu mir nehmen, damit auch ihr seid, wo ich bin" (Johannes 14:2-3). Und deshalb sagt Jesus nach seiner Auferstehung, dass er jetzt auf zu seinem Vater fährt. Und der Vater des Bräutigams ist auch der (Adoptiv-) Vater der Braut (Johannes 20:17).

**Phase 3**: Eines Tages wird Jesus seine Braut holen. Er wird von einer Engelseskorte begleitet werden, der ein Ruf vorausgeht, wenn er für die Gemeinde wiederkommt (1. Thessalonicher 4:16). Wir wissen nicht, wann genau das geschehen wird; wir müssen, wie die Braut, bereit sein und treu bleiben. Das ist der Kontext des Gleichnisses von den zehn Jungfrauen mit ihren Öllampen, die auf den Bräutigam warten (Matthäus 25). In diesem Gleichnis sind wir diese Jungfrauen, die auf den Bräutigam wachten. Dann kommt das fröhliche ewige Hochzeitsfest, auch Hochzeit des Lammes genannt (Offenbarung 19:6-9). Das ist der Kontext des Gleichnisses vom königlichen Hochzeitsmahl (Matthäus 22), wo ein König, das Hochzeitsfest für seinen Sohn organisiert und dafür Gäste sucht. In diesem Gleichnis sind wir die Hochzeitsgäste!

Im Hinblick auf die jüdische Hochzeitstradition ist folgendes ganz klar:

* der Bund Jesu mit der Gemeinde ist fest! Die Gemeinde ist für Jesus bestimmt.
* die Gemeinde soll rein für Jesu bleiben. Sie soll leidenschaftlich auf ihn warten.
* Jesus musste zum Vater zurück, sonst wo hätte die Gemeinde wohnen können?
* Jesus wird wiederkommen und es wird eine fröhliche Überraschung.
* Ein riesiges fröhliches Fest wartet auf uns!



    
